# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef4898d47e966da06caf2bdbcc3d50657fbf43d54fd6ee2e53a730a1d064eac4ccb4f147d4bed7af3bb8d8f714b9643e91b3bdfe53a6908bbfdf310a2d15d1d2

test:
  secret_key_base: e80d57cff90ee57d8de6c843bcd56d613717c234760cfd8e8d1dca4032525606bd21f7b03ed049c90ca1472233f4c9b5ac38ec5a752a1dfb721b1e6c9e1151b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
